### PR TITLE
Add Reddit icon to social links

### PR DESCRIPTION
**Pull request by alessandrojean**
image

### CODE REVIEW

**Comment by Soitora** [comment]
Any reason you did not use the built-in icons instead of adding your own?

**Comment by alessandrojean** [comment]
> Any reason you did not use the built-in icons instead of adding your own?

VitePress doesn't have an out-of-box icon for Reddit and neither X. Icons used are from [Simple Icons](https://simpleicons.org/), I forgot to mention btw.

Reference: https://vitepress.dev/reference/default-theme-config#sociallinks

**Comment by Soitora** [comment]
> > Any reason you did not use the built-in icons instead of adding your own?
> 
> VitePress doesn't have an out-of-box icon for Reddit and neither X. Icons used are from [Simple Icons](https://simpleicons.org/), I forgot to mention btw.
> 
> Reference: https://vitepress.dev/reference/default-theme-config#sociallinks

Odd that they don't have Reddit, but they do have X as of https://github.com/vuejs/vitepress/commit/0c8cf0df8903b3f48ccffa17c92fc988d88b7ad7

Their built-in icon felt too big when I tried it, yours looks fine in the screenshot 

The reason I didn't switch to X myself is I'm not sure we wanna support the rebrand, haven't seen many places change it.

Maybe we poll it in the Discord?

**Comment by alessandrojean** [comment]
Ah, haven't saw the Twitter one, will undo that part.

**Pull request merged**
