### PR TITLE
Change features icons

### PR DESCRIPTION
**Pull request by Soitora**
See PR url

Should "Customization" be given its own unique icon, like, the [Palette](https://pictogrammers.com/library/mdi/icon/palette-outline/) icon used for Appearance menu? Or maybe the [Pencil-Ruler](https://pictogrammers.com/library/mdi/icon/pencil-ruler-outline/) icon?

### CODE REVIEW

**Comment by arkon** [comment]
Maybe:

- Tracking: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:sync:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=sync
- Extensions: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:extension:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=puzzle
- Customization: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:tune:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=custom

**Comment by alessandrojean** [comment]
Arkon's suggestions seems good.

**Comment by Soitora** [comment]
Updated the icons

Maybe the app should have their updated? Noticed a clear difference between the latest Material Icons and what we're using now

image
 vs
image

**Comment by arkon** [comment]
We're just using whatever the official library provides, so presumably that'll need to happen upstream.

**Review by arkon — APPROVED** [review]

**Pull request merged**
